=== oracle-samples/oic-rab-vscode/schemas/mainADD_v01.json
{
  "_comment": "Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved. This software is licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl.",
  "$id": "#schema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ADD Specification",
  "description": "ADD specification",
  "type": "object",
  "required": [
    "info",
    "connection"
  ],
  "properties": {
    "info": {
      "$ref": "info_v01.json"
    },
    "connection": {
      "$ref": "connection_v01.json"
    },
    "schemas": {
      "$ref": "schemas_v01.json"
    },
    "categories": {
      "$ref": "categories_v01.json"
    },
    "actions": {
      "$ref": "actions_v01.json"
    },
    "triggers": {
      "$ref": "triggers_v01.json"
    },
    "flows": {
      "$ref": "flows_v01.json"
    }
  },
  "additionalProperties": false,
  "allOf": [
    {
      "$comment": "must have at least one trigger in absence of actions.",
      "if": {
        "not": {
          "required": [
            "actions"
          ],
          "properties": {
            "actions": {
              "minProperties": 1
            }
          }
        }
      },
      "then": {
        "required": [
          "triggers"
        ],
        "properties": {
          "triggers": {
            "minProperties": 1
          }
        }
      }
    },
    {
      "$comment": "must have at least one action in absence of triggers.",
      "if": {
        "not": {
          "required": [
            "triggers"
          ],
          "properties": {
            "triggers": {
              "minProperties": 1
            }
          }
        }
      },
      "then": {
        "required": [
          "actions"
        ],
        "properties": {
          "actions": {
            "minProperties": 1
          }
        }
      }
    }
  ],
  "definitions": {}
}

=== oracle-samples/oic-rab-vscode/scaffold/definitions/main.add.json
{
  "info": {
    "specVersion": "1.0",
    "id": "",
    "displayName": "",
    "description": "",
    "version": "1.0.0",
    "categories": [],
    "appInfo": {
      "name": "",
      "description": "",
      "contactUS": "",
      "supportURL": "",
      "documentationURL": ""
    },
    "publisherInfo": {
      "name": "",
      "description": "",
      "contactUS": "",
      "supportURL": "",
      "documentationURL": ""
    },
    "settings": {
      "supportsConnectivityAgent": false
    }
  },
  "connection": {},
  "actions": {},
  "flows": {},
  "schemas": {}
}
